import { existsSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { Command } from 'commander'
import chalk from 'chalk'

/**
 * Register the `synclite init` command.
 * Scaffolds the minimal files needed to start using Synclite.
 */
export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Set up Synclite in the current project')
    .option('--framework <name>', 'Framework: react | vue | react-native | vanilla', 'react')
    .action((opts: { framework: string }) => {
      const cwd = process.cwd()
      const framework = opts.framework as 'react' | 'vue' | 'react-native' | 'vanilla'

      console.log()
      console.log(chalk.bold('Synclite init'))
      console.log(chalk.dim(`Framework: ${framework}\n`))

      // Write a .env.local with a placeholder relay URL
      const envPath = join(cwd, '.env.local')
      if (!existsSync(envPath)) {
        writeFileSync(envPath, 'NEXT_PUBLIC_RELAY_URL=ws://localhost:8080\n')
        console.log(chalk.green('✔') + '  Created .env.local')
      } else {
        console.log(chalk.dim('·  .env.local already exists — skipped'))
      }

      // Write a starter file
      const srcDir = join(cwd, 'src')
      if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true })

      const starterPath = join(srcDir, 'synclite.ts')
      if (!existsSync(starterPath)) {
        writeFileSync(starterPath, starterFile(framework))
        console.log(chalk.green('✔') + '  Created src/synclite.ts')
      } else {
        console.log(chalk.dim('·  src/synclite.ts already exists — skipped'))
      }

      console.log()
      console.log(chalk.bold('Next steps:'))
      console.log(
        `  1. ${chalk.cyan('synclite relay dev')}  — start a local relay`,
      )
      console.log(
        `  2. Import ${chalk.cyan(`@synclite/${framework === 'vanilla' ? 'core' : framework}`)} and wrap your app`,
      )
      console.log(
        `  3. ${chalk.cyan('synclite relay deploy --platform fly')}  — ship to production`,
      )
      console.log()
    })
}

function starterFile(framework: 'react' | 'vue' | 'react-native' | 'vanilla'): string {
  switch (framework) {
    case 'react':
      return `// src/synclite.ts — generated by synclite init
// Wrap your root component with <SyncliteProvider> to enable sync.

export { SyncliteProvider, useSynclite, useValue, useQuery, useStatus } from '@synclite/react'
`
    case 'vue':
      return `// src/synclite.ts — generated by synclite init
// Install the plugin in main.ts: app.use(createSynclite({ relay: process.env.VITE_RELAY_URL }))

export { createSynclite, useSynclite, useValue, useQuery, useStatus } from '@synclite/vue'
`
    case 'react-native':
      return `// src/synclite.ts — generated by synclite init
// Wrap your root component with <SyncliteProvider> to enable offline-first sync.

export { SyncliteProvider, useSynclite, useValue, useQuery, useStatus } from '@synclite/react-native'
`
    default:
      return `// src/synclite.ts — generated by synclite init
import { Synclite } from '@synclite/core'

const relay = process.env['RELAY_URL'] ?? 'ws://localhost:8080'

export const db = new Synclite({ relay, appId: 'my-app' })
`
  }
}
